export const products = [
    {
        "id": 1,
        "name": "Polo de manga corta en algodon sostenible para chico",
        "slug": "polo-de-manga-corta-en-algodon-sostenible-para-chico",
        "price": 12.99,
        "sales": 0.5,
        "type": "Polos",
        "colors": ["green", "white", "black"],
        "image": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1671637729/23-00890-082-XL-4/polo-de-manga-corta-en-algodon-sostenible-para-chico-hoja-XL-4.jpg",
        "image_back": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_750/v1671637736/23-00890-082-XL-5/polo-de-manga-corta-en-algodon-sostenible-para-chico-hoja-XL-5.jpg",
        "image_black": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1673872589/23-03147-046-XL-4/polo-de-manga-corta-con-cuello-mao-en-algodon-para-nino-lapiz-XL-4.jpg",
        "image_white": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1675759936/23-54110-700-XL-4/polo-granito-cuello-mao-de-algodon-sostenible-para-nino-blanco-XL-4.jpg",
    },
    {
        "id": 2,
        "name": "Polo de manga corta sostenible para chico",
        "slug": "polo-de-manga-corta-sostenible-para-chico",
        "price": 13.99,
        "sales": null,
        "type": "Polos",
        "colors": ["blue", "white"],
        "image": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1671637593/23-00150-089-XL-4/polo-manga-corta-granito-basico-nino-petalo-XL-4.jpg",
        "image_back": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1671637671/23-00102-048-XL-5/polo-granito-basico-bebe-navidad-XL-5.jpg",
        "image_white": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1671637772/23-00150-091-XL-4/polo-manga-corta-granito-basico-nino-blanco-XL-4.jpg",
    },
    {
        "id": 3,
        "name": "Polo manga larga estampado blanco",
        "slug": "polo-manga-larga-estampado-blanco",
        "price": 18.99,
        "sales": 0.25,
        "type": "Polos",
        "colors": ["black", "white", "blue"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-ecofriends-estampado-manga-larga-bebe-nino_id_11-02142-013-M-4.JPG?v=20210831093313",
        "image_back": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1675759919/23-54110-700-XL-5/polo-granito-cuello-mao-de-algodon-sostenible-para-nino-blanco-XL-5.jpg",
        "image_white": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1675759936/23-54110-700-XL-4/polo-granito-cuello-mao-de-algodon-sostenible-para-nino-blanco-XL-4.jpg",
    },
    {
        "id": 4,
        "name": "Polo manga larga miniestampado blanco",
        "slug": "polo-manga-larga-miniestampado-blanco",
        "price": 24.99,
        "sales": null,
        "type": "Polos",
        "colors": ["white"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-manga-larga-contrastes-chico_id_11-07145-073-M-4.JPG?v=20210921061532",
        "image_back": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_600/v1675759919/23-54110-700-XL-5/polo-granito-cuello-mao-de-algodon-sostenible-para-nino-blanco-XL-5.jpg",
    },
    {
        "id": 5,
        "name": "Polo manga larga estampado rojo",
        "slug": "polo-manga-larga-estampado-rojo",
        "price": 23.99,
        "sales": 0.2,
        "type": "Polos",
        "colors": ["black", "white", "red"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-ecofriends-manga-larga-bebe-nino_id_11-02139-950-M-4.JPG?v=20210428111531",
    },
    {
        "id": 6,
        "name": "Polo manga larga estrella",
        "slug": "polo-manga-larga-estrella",
        "price": 19.99,
        "sales": null,
        "type": "Polos",
        "colors": ["white"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-ecofriends-manga-larga-skate-nino_id_11-04155-071-M-4.JPG?v=20210630052817",
    },
    {
        "id": 7,
        "name": "Polo manga larga verde",
        "slug": "polo-manga-larga-verde",
        "price": 4.99,
        "sales": null,
        "type": "Polos",
        "colors": ["black", "white", "green"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-manga-larga-print-nino_id_11-04159-030-M-4.JPG?v=20210827045329",
    },
    {
        "id": 8,
        "name": "Polo manga larga granate",
        "slug": "polo-manga-larga-granate",
        "price": 25.99,
        "sales": 0.5,
        "type": "Polos",
        "colors": ["black", "white", "red"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-ecofriends-manga-larga-skate-nino_id_11-04155-072-M-4.JPG?v=20210630052817",
    },
    {
        "id": 9,
        "name": "Polo manga larga rayas",
        "slug": "polo-manga-larga-rayas",
        "price": 15.99,
        "sales": null,
        "type": "Polos",
        "colors": ["black", "white", "blue"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-manga-larga-raya-bloque-nino_id_11-04156-088-M-4.JPG?v=20210730111904",
    },
    {
        "id": 10,
        "name": "Polo manga larga cuadros",
        "slug": "polo-manga-larga-cuadros",
        "price": 12.99,
        "sales": null,
        "type": "Polos",
        "colors": ["black", "white", "blue"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-desagujado-blocking-nino_id_11-55119-700-M-4.JPG?v=20210921062305",
    },
    {
        "id": 11,
        "name": "Polo manga larga azul marino",
        "slug": "polo-manga-larga-azul-marino",
        "price": 9.99,
        "sales": 0.3,
        "type": "Polos",
        "colors": ["black", "white", "blue"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo--ecofriends-manga-larga-estampado-nino_id_11-04158-097-M-4.JPG?v=20210720044159",
    },
    {
        "id": 12,
        "name": "Polo manga larga bandas",
        "slug": "polo-manga-larga-bandas",
        "price": 30.99,
        "sales": null,
        "type": "Polos",
        "colors": ["black", "white", "goldenrod"],
        "image": "https://media.mayoral.com/wcsstore/mayoral/images/catalog/mayoral/polo-bandas-nino_id_11-55120-700-M-4.JPG?v=20210729043620",
    },
    {
        "id": 13,
        "name": "P*l* paginación filter test",
        "slug": "pl-paginacion-filter-test",
        "price": 99.99,
        "sales": 0.5,
        "type": "Polos",
        "colors": ["green", "white", "black"],
        "image": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_960/v1671637729/23-00890-082-XL-4/polo-de-manga-corta-en-algodon-sostenible-para-chico-hoja-XL-4.jpg",
        "image_back": "https://assets.mayoral.com/images/t_auto_img,f_auto,c_limit,w_750/v1671637736/23-00890-082-XL-5/polo-de-manga-corta-en-algodon-sostenible-para-chico-hoja-XL-5.jpg",
    }
];
